### ISSUE TITLE
希望优化搜索结果

### ISSUE THREAD

**Issue by x2287711259** [wy580477/musicn-container#1]
大佬，能否参考一下这个项目 https://github.com/foamzou/melody
希望可以把各个平台搜索结果直接显示在一个界面上，这个项目很好用，但是无法在国外vps部署使用

**Comment by wy580477** [comment]
我只是简单写了个dockerfile，功能方面问题建议去原作者的 repo 提议： https://github.com/zonemeen/musicn

国内服务限制境外 ip 访问这个没办法，政策、版权都有原因。

**Comment by x2287711259** [comment]
哦，谢谢
